<a href="https://colab.research.google.com/github/chemkai/30-Days-of-ML-basics/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Creating a matrix using Numpy**

In [5]:
matrix_1 = np.array([[2,3], [6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


(2, 2)

In [6]:
matrix_1.shape

(2, 2)

In [7]:
matrix_2 = np.array([[11,34,41], [34,23,12], [32,21,56]])
print(matrix_2)

[[11 34 41]
 [34 23 12]
 [32 21 56]]


In [8]:
matrix_2.shape

(3, 3)

**Creating Matrices with random value**

In [9]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.89523877 0.0531197  0.54302853]
 [0.37340036 0.41832004 0.4155465 ]
 [0.4762376  0.93136509 0.7844263 ]]


In [14]:
# Creating a matrix with random integer values
random_int_matrix = np.random.randint(100,size=(3,4))
print(random_int_matrix)

[[79 75 76  4]
 [56 65 13  1]
 [96 24 21 94]]


**Matrix with all the values as 1**

In [12]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Matrix with integer 1
matrix_4 = np.ones((2,3), dtype=int)
print(matrix_4)

[[1 1 1]
 [1 1 1]]


In [18]:
# Matrix with float
matrix_5 = np.ones((2,3), dtype=float)
print(matrix_5)

[[1. 1. 1.]
 [1. 1. 1.]]


**Null matrix OR Zero matrix**

In [19]:
matrix_6 = np.zeros((3,4))
print(matrix_6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Identity Matrix**

In [20]:
indentity_Matrix = np.eye(3,3)
print(indentity_Matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# Identity matrix with integer values
indentity_Matrix = np.eye(3,3,dtype=int)
print(indentity_Matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Transpose of a matrix**

In [24]:
# Matrix with random integer values
matrix_7 = np.random.randint(100,size=(5,6))
print(matrix_7)

[[ 6 14 92 25 60 99]
 [18 24 77 26 61 84]
 [60 87 61 45 14  0]
 [35 14 40 99 55 24]
 [88 28 17 67 90 21]]


In [25]:
# Transpose of a matrix
transpose_matrix = np.transpose(matrix_7)
print(transpose_matrix)

[[ 6 18 60 35 88]
 [14 24 87 14 28]
 [92 77 61 40 17]
 [25 26 45 99 67]
 [60 61 14 55 90]
 [99 84  0 24 21]]
