<a href="https://colab.research.google.com/github/chemkai/30-Days-of-ML-basics/blob/main/Matrix_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Matrix Addition**
**Note**
 * two matrices can be added only if they're of same shape

In [2]:
# Creating two matrices
A = np.array([[2,3], [4,5]])
B = np.array([[4,5], [6,7]])
print("A\n", A)
print("B\n",B)

A
 [[2 3]
 [4 5]]
B
 [[4 5]
 [6 7]]


In [3]:
sum = A+B
print(sum)

[[ 6  8]
 [10 12]]


In [6]:
# Creating 2 matrices with random values
matrix_1 = np.random.randint(100, size=(3,4))
matrix_2 = np.random.randint(100, size=(3,4))
print("Matrix_1\n\n",matrix_1)
print("\nMatrix_2\n\n",matrix_2)

Matrix_1

 [[69 20 12 75]
 [93 86 43 82]
 [34 43  2 89]]

Matrix_2

 [[50 67 36 50]
 [77 64 93 77]
 [13 15 85 36]]


In [7]:
sum = np.add(matrix_1, matrix_2)
print(sum)

[[119  87  48 125]
 [170 150 136 159]
 [ 47  58  87 125]]


**Matrix subtraction**

In [8]:
# Creating 2 matrices with random values
matrix_1 = np.random.randint(100, size=(3,4))
matrix_2 = np.random.randint(100, size=(3,4))
print("Matrix_1\n\n",matrix_1)
print("\nMatrix_2\n\n",matrix_2)

Matrix_1

 [[ 7 47 99 35]
 [ 5 59 96  0]
 [56 43 47 45]]

Matrix_2

 [[80 50 87 56]
 [25 40 27 42]
 [78 74 30 32]]


In [9]:
sum = np.subtract(matrix_1, matrix_2)
print(sum)

[[-73  -3  12 -21]
 [-20  19  69 -42]
 [-22 -31  17  13]]


**Mutiplying a vector with a scalar**

In [11]:
# Creating a matrix with random values
matrix_1 = np.random.randint(100, size=(3,4))
a = 6
print("Matrix_1\n\n",matrix_1)

Matrix_1

 [[77 58 11 77]
 [91 58 57 53]
 [98 23 51 56]]


In [12]:
sum = np.multiply(a,matrix_1)
print(sum)

[[462 348  66 462]
 [546 348 342 318]
 [588 138 306 336]]


**Multiplying 2 matrices**
**Note**
* number of columns of 1st matrix must be equal to rows of 2nd matrix

In [13]:
# Creating 2 matrices with random values
matrix_1 = np.random.randint(100, size=(3,4))
matrix_2 = np.random.randint(100, size=(4,2))
print("Matrix_1\n\n",matrix_1)
print("\nMatrix_2\n\n",matrix_2)

Matrix_1

 [[49 62 44 10]
 [26 88 81 47]
 [57 22 13 26]]

Matrix_2

 [[ 3 86]
 [31 64]
 [77 72]
 [45 72]]


In [15]:
sum = np.dot(matrix_1, matrix_2)
print(sum)

[[ 5907 12070]
 [11158 17084]
 [ 3024  9118]]


**Element wise Matrix multiplication**
**NOTE**
* number of rows and columns of both the matrices must be equal

In [16]:
# Creating 2 matrices with random values
matrix_1 = np.random.randint(100, size=(3,4))
matrix_2 = np.random.randint(100, size=(3,4))
print("Matrix_1\n\n",matrix_1)
print("\nMatrix_2\n\n",matrix_2)

Matrix_1

 [[47 86 48 72]
 [58 51 96 10]
 [61 35 18 67]]

Matrix_2

 [[30  0 57 33]
 [33 47 65 66]
 [12 44 29 45]]


In [18]:
sum = np.multiply(matrix_1, matrix_2)
print(sum)

[[1410    0 2736 2376]
 [1914 2397 6240  660]
 [ 732 1540  522 3015]]
